#sonar.projectKey=atul5021_trivy-ansible_2643cb9e-4b2a-47ec-97ca-7ede2961cd73

sonar.projectKey=trivy-ansible
sonar.projectName=trivy-ansible
sonar.sources=.

# Force SonarQube to treat YAML files as scanned code
sonar.inclusions=**/*.yml,**/*.yaml,**/*.cfg,hosts
