sonar.projectKey=trivy-ansible
sonar.projectName=trivy-ansible
sonar.sources=.

# Include all extension files explicitly
sonar.inclusions=**/*

# Force SonarQube to parse YAML files
sonar.yaml.file.suffixes=.yaml,.yml
